name: base
dependencies:
  - conda-forge::pandas

  - conda-forge::r-base=4.1
  - conda-forge::r-rcolorbrewer
  - conda-forge::r-tidyverse
  - conda-forge::r-reshape2
  - conda-forge::r-ggpubr
  - conda-forge::r-ggridges
  - conda-forge::r-viridis
